AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  postrecipes:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 10
      Role: 'arn:aws:iam::285095874699:role/service-role/post-recipes-role-eeqo75h5'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /recipes
            Method: POST
        Api2:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
